// Comprehensive list of world languages used by the freelancer
// application form. Covers major world languages PLUS a broad set of
// African and Asian languages we actively recruit for. Sorted
// alphabetically. Same list is used for native-language and language-pair
// dropdowns so the source/target sides match.
export const LANGUAGES: string[] = [
  "Afrikaans",
  "Akan (Twi)",
  "Albanian",
  "Amharic",
  "Arabic",
  "Arabic (Egyptian)",
  "Arabic (Gulf)",
  "Arabic (Levantine)",
  "Arabic (Maghrebi)",
  "Arabic (Modern Standard)",
  "Armenian",
  "Assamese",
  "Azerbaijani",
  "Bambara",
  "Basque",
  "Belarusian",
  "Bemba",
  "Bengali",
  "Berber (Tamazight)",
  "Bhojpuri",
  "Bosnian",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Cebuano",
  "Chichewa (Nyanja)",
  "Chinese (Cantonese)",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Chinese (Wu / Shanghainese)",
  "Croatian",
  "Czech",
  "Danish",
  "Dari",
  "Dutch",
  "Dzongkha",
  "English",
  "English (British)",
  "English (US)",
  "Estonian",
  "Ewe",
  "Fante",
  "Faroese",
  "Filipino (Tagalog)",
  "Finnish",
  "French",
  "French (Canadian)",
  "Fula (Fulfulde)",
  "Ga",
  "Galician",
  "Georgian",
  "German",
  "German (Austrian)",
  "German (Swiss)",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Ilocano",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kashmiri",
  "Kazakh",
  "Khmer",
  "Kikuyu",
  "Kinyarwanda",
  "Kirundi",
  "Konkani",
  "Korean",
  "Kurdish (Kurmanji)",
  "Kurdish (Sorani)",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Luganda",
  "Luxembourgish",
  "Macedonian",
  "Maithili",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Mandinka",
  "Maori",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Northern Sotho (Sepedi)",
  "Norwegian",
  "Norwegian (Bokmål)",
  "Norwegian (Nynorsk)",
  "Odia (Oriya)",
  "Oromo",
  "Pashto",
  "Persian (Farsi)",
  "Polish",
  "Portuguese",
  "Portuguese (Brazilian)",
  "Portuguese (European)",
  "Punjabi",
  "Quechua",
  "Romanian",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Scottish Gaelic",
  "Sepedi",
  "Serbian",
  "Sesotho",
  "Setswana",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish",
  "Spanish (Latin American)",
  "Spanish (Mexican)",
  "Spanish (Castilian)",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tagalog",
  "Tajik",
  "Tamazight",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tongan",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Welsh",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];
